#- name: myhaproxy
#  src: geerlingguy.haproxy
#- name: myahproxy2
#  src: https://github.com/geerlingguy/ansible-role-haproxy/archive/1.3.1.tar.gz
- name: myhaproxy3
  src: https://github.com/geerlingguy/ansible-role-haproxy.git